=== alejandromagnorsky/tpepdc/trunk/src/settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.0">

	<xsd:complexType name="XMLTransformation">
		<xsd:attribute name="rotate" type="xsd:boolean"></xsd:attribute>
		<xsd:attribute name="leet" type="xsd:boolean"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="XMLEraseSettings">
		<xsd:sequence>
			<xsd:element name="date" type="XMLDateRestriction" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="sender" type="xsd:string" maxOccurs="unbounded"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="header-pattern" type="xsd:string"
				maxOccurs="unbounded" minOccurs="0">
			</xsd:element>
			<xsd:element name="content-type" type="xsd:string"
				maxOccurs="unbounded" minOccurs="0">
			</xsd:element>
			<xsd:element name="size-bytes" type="XMLSizeRestriction"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="structure" type="xsd:string"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="XMLSettings">
		<xsd:sequence>
			<xsd:element name="user" type="XMLUser" maxOccurs="unbounded"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="blacklist" type="XMLIPBlacklist"></xsd:element>

		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="XMLProxySettings" type="XMLSettings"></xsd:element>

	<xsd:complexType name="XMLUser">
		<xsd:sequence>
			<xsd:element name="erase-settings" type="XMLEraseSettings"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="transform-settings" type="XMLTransformation"
				maxOccurs="1" minOccurs="0">
			</xsd:element>

			<xsd:element name="schedule" type="XMLScheduleRestriction"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="server" type="xsd:string" maxOccurs="1"
				minOccurs="1">
			</xsd:element>

		</xsd:sequence>

		<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="max-logins" type="xsd:int"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="XMLSizeRestriction">
    	<xsd:sequence>
    		<xsd:element name="from" type="xsd:int" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="to" type="xsd:int" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="XMLDateRestriction">
    	<xsd:sequence>
    		<xsd:element name="from" type="xsd:date" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="to" type="xsd:date" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="XMLIPBlacklist">
    	<xsd:sequence>
    		<xsd:element name="ip" maxOccurs="unbounded" minOccurs="0">
    			<xsd:simpleType >
    				<xsd:restriction base="xsd:string">
    					<xsd:pattern
    						value="[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(\/[0-9]{2})?">
    					</xsd:pattern>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="XMLScheduleRestriction">
    	<xsd:sequence>
    		<xsd:element name="from" maxOccurs="1" minOccurs="0">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:int">
    					<xsd:minInclusive value="0"></xsd:minInclusive>
    					<xsd:maxInclusive value="1440"></xsd:maxInclusive>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    		<xsd:element name="to" maxOccurs="1" minOccurs="0">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:int">
    					<xsd:minInclusive value="0"></xsd:minInclusive>
    					<xsd:maxInclusive value="1440"></xsd:maxInclusive>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


</xsd:schema>

=== alejandromagnorsky/tpepdc/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<XMLProxySettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="settings.xsd">
	<user max-logins="99" name="tpepdc">
		<erase-settings>
			<date>
				<from>2001-01-01</from>
				<to>2001-01-01</to>
			</date>
			<sender>sender</sender>
			<header-pattern>header-pattern</header-pattern>
			<content-type>content-type</content-type>
			<size-bytes>
				<from>0</from>
				<to>0</to>
			</size-bytes>
			<structure>structure</structure>
		</erase-settings>
		<transform-settings leet="true" />
		<schedule>
			<from>0</from>
			<to>1400</to>
		</schedule>
		<server>server</server>
	</user>
	<blacklist>
		<ip>255.255.255.2</ip>
	</blacklist>
</XMLProxySettings>
